version: "3"
services:
  api-server:
    image: api-server
    ports:
      - "5000:5000"
        #networks:
        #- movies-app
        #depends_on:
        #- mongo
        #networks:
        #movies-app:
        #driver: bridge
        #volumes:
        #mongo-data:
        #driver: local
